version: '3.8'

services:

  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - /src:/var/www
    networks:
      - mired
  db:
    image: mysql:5.7
    container_name: travellist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - mired

  nginx:
    image: nginx:alpine    
    restart: unless-stopped    
	ports:
	  -8000:80
	volumenes:
	 - ./src:/var/www/html
	 - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  networks:
    - mired



  db:
  #composer:
  #artisan:
  #npm:
  networks:
    - mired
  
